import '@ui/styles/globals.css'
import type { Metadata } from 'next'
import { Inter } from 'next/font/google'

const inter = Inter({ subsets: ['latin'] })

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}): JSX.Element {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav className="bg-neutral-700 px-2 py-4 text-white">
          <ul>
            <li>
              <a href="/">Home</a>
            </li>
          </ul>
        </nav>
        <div className="p-2 md:p-4">{children}</div>
      </body>
    </html>
  )
}
